services:
  redis:
    image: redis:7-alpine
    container_name: lab5-redis
    ports:
      - "6379:6379"

  image-resizer:
    build: ./functions/image_resizer
    container_name: lab5-image-resizer
    ports:
      - "5001:5000"
    volumes:
      - ./data:/data

  notifier:
    build: ./functions/notifier
    container_name: lab5-notifier
    ports:
      - "5002:5000"

  event-router:
    build: ./router
    container_name: lab5-event-router
    depends_on:
      - redis
      - image-resizer
      - notifier
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./data:/data

  event-source:
    build: ./event_source
    container_name: lab5-event-source
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - WATCH_DIR=/data/input
    volumes:
      - ./data:/data
